name: "Capture Vercel Preview URL"
author: "Mandeep Ch"
description: "Capture a Vercel preview URL and feed it into your next GitHub action."
branding:
  icon: "triangle"
  color: "green"
inputs:
  GITHUB_TOKEN:
    description: "GitHub actions token to cancel the action in case preview URL could not be found. If not specified, the action will explicitly fail."
    required: false
    default: ""
  PAT:
    description: "Personal Access Token to access repository issue comments"
    required: true
    default: ""
  preview_url_regexp:
    description: "Regular expression pattern to capture the preview URL. Ensure first capture group captures the preview URL."
    required: false
    default: 'Preview: \[(.*)\]' # Do use single quotes, do NOT use delimiters.
outputs:
  vercel_preview_url:
    description: "The preview URL for the pull request's Vercel deployment."
runs:
  using: "node12"
  main: "dist/index.js"
